### ISSUE TITLE
python util.py报错

### ISSUE THREAD

**Issue by liuyongfei1** [wangshunping/weibo_spider#9]
执行：python util.py,报：
BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))
Traceback (most recent call last):
  File "util.py", line 134, in <module>
    main()
  File "util.py", line 120, in main
    firstInfo = getUniversityStudent(mainid, school)
  File "util.py", line 58, in getUniversityStudent
    personalInfo = divlabel[0].next_sibling.get_text('|',strip=True)
IndexError: list index out of range

**Comment by Davidchent** [comment]
我的也报这个错，我检查了下，可能是编码不对，或者没有登陆成功 
请问你的解决了吗？
